# --- Sebulba config ---

# --- Training ---
seed: 42  # RNG seed.
total_num_envs: 2048  # Total Number of vectorised environments across all actors. Needs to be divisible by the number of actor devices and actors per device.
total_timesteps: 1e7 # Set the total environment steps.
# If unspecified, it's derived from num_updates; otherwise, num_updates adjusts based on this value.
num_updates: ~ # Number of updates

# Define the number of actors per device and which devices to use.
actor:
  device_ids: [0, 1]
  actor_per_device: 2

# Define which devices to use for the learner.
learner:
  device_ids: [2, 3]

# --- Evaluation ---
num_eval_episodes: 128 # Number of episodes to evaluate per evaluation.
evaluator_device_id: 0 # Device to use for evaluation.
absolute_metric: True # Whether the absolute metric should be computed. For more details
  # on the absolute metric please see: https://arxiv.org/abs/2209.10485
