# ---Environment Configs---
env_name: envpool # Used for logging purposes and selection of the corresponding wrapper.

scenario:
  name: LunarLander-v2
  task_name: lunarlander # For logging purposes.

kwargs: {}

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return
